# Navbar Menus
[[nav]]
name = "about"
url = "ofilibre/"
weight = 2

[[nav]]
name = "activities"
url = "acciones/"
weight = 3

[[nav]]
name = "resources"
url = "recursos/"
weight = 4
hasChildren = true

  [[nav]]
  parent = "resources"
  name = "Teaching Materials Catalogue"
  url = "catalogo/"
  weight = 1

  [[nav]]
  parent = "resources"
  name = "Guides"
  url = "guias/"
  weight = 2

  [[nav]]
  parent = "resources"
  name = "Sheets"
  url = "fichas/"
  weight = 3

  [[nav]]
  parent = "resources"
  name = "Presentations"
  url = "pres/"
  weight = 4

  [[nav]]
  parent = "resources"
  name = "OfiLibre Code"
  url = "https://gitlab.eif.urjc.es/ofilibre/code"
  weight = 5
  target = "_blank"

[[nav]]
name = "blog"
url = "blog/"
weight = 5

[[nav]]
name = "contact"
url = "contacto/"
weight = 6

[[nav]]
name = "search"
url = "buscar/"
weight = 7

# Footer actions Menu
[[actions]]
name = "graphicdesign"
url = "acciones/"
weight = 1

[[actions]]
name = "webdesign"
url = "acciones/"
weight = 2

[[actions]]
name = "webdevelopment"
url = "acciones/"
weight = 3

# Footer Quick links Menu
[[quicklink]]
name = "partners"
url = "ofilibre/"
weight = 1

[[quicklink]]
name = "ofilibre"
url = "ofilibre/"
weight = 2

[[quicklink]]
name = "faqs"
url = "ofilibre/"
weight = 3

[[quicklink]]
name = "badges"
url = "ofilibre/"
weight = 4