backend:
  name: git-gateway
  branch: master
media_folder: static/images
public_folder: /images
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/espanol/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'date' }
      - { label: 'Descripción', name: 'description', widget: 'string' }
      - {label: 'URL', name: 'slug', widget: 'string'}
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'post'}
      - { label: 'Categorías', name: 'categories', widget: 'hidden', default: ["OfiLibre"]}
      - { label: 'Tags', name: 'tags', widget: 'list'}
      - { label: 'Imagen de fondo del post (alargada)', name: 'bg_image', widget: 'image', default: '/images/guias/openaccess-square.png'}
      - { label: 'Imagen cuadrada para la portada', name: 'thumb', widget: 'image', default: '/images/guias/openaccess-square.png'}
      - { label: 'Cuerpo del post', name: 'body', widget: 'markdown' }
  - name: 'guias'
    label: 'Guías'
    folder: 'content/espanol/guias'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Logo', name: 'logo', widget: 'image' }
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'guias'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
